SET DATABASE SQL SYNTAX ORA TRUE;
drop table uzytkownik if exists;
create table uzytkownik(
	uzytkownik_id integer primary key GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1),
	firstname varchar(50) not null,
	lastname varchar(50) not null,
	login varchar(50) not null,
	password varchar(100) not null
);

drop table follower if exists;
create table follower(
	follower_id integer,
	followee_id integer
);

drop table wpis if exists;
create table wpis(
	wpis_id integer primary key GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1),
	author_id integer not null,
	wpis_date timestamp,
	text varchar(150) not null
);




